# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: doc/html
  github-token: $GH_REPO_TOKEN
  repo: jeremylt/autoDMDocumentation
  target-branch: master
  on:
    branch: master
